### PR TITLE
Add the ability to use different port numbers per tenant

### PR DESCRIPTION
**Pull request by mattgresham**
In order to be able to select the correct port that a connection to a terminal should be made on, this change will add a `getConnectionAddress` method that will use the `tenantCode` to determine the port that should be added (or not) to the EFTPOS address.

### CODE REVIEW

**Review by mx51damon — DISMISSED** [review]
lgtm~

**Review by RaymondK-mx51 — DISMISSED** [review]
Thanks Matt

**Review by mx51damon — DISMISSED** [review]

**Review by RaymondK-mx51 — COMMENTED** [review]
any reason that the version is now hardcoded and version gone backwards?

**Comment by mx51damon** [comment]
> any reason that the version is now hardcoded and version gone backwards?

Hi @RaymondK-mx51, currently @gopipatell has reverted the changes back and this task is working in progress. We will let you to review on it once we are ready.

Cheers ~

**Review by mx51damon — APPROVED** [review]
This time should be good to go ~

**Review by RaymondK-mx51 — APPROVED** [review]
Well done

**Pull request merged**
